#ifndef OTA_Software_Update_h
#define OTA_Software_Update_h

// Local includes.
#include "Attribute_Request.h"
#include "IAPI_Implementation.h"
#include "OTA_Firmware_Update.h"
#include "OTA_Handler.h"
#include "Shared_Attribute_Update.h"

uint8_t constexpr MAX_SW_TOPIC_SIZE = 33U;
uint8_t constexpr SW_OTA_ATTRIBUTE_KEYS_AMOUNT = 5U;
char constexpr NO_SW_REQUEST_RESPONSE[] =
    "Did not receive requested shared attribute software keys. Ensure keys "
    "exist and device is connected";
// Software topics.
char constexpr SOFTWARE_RESPONSE_TOPIC[] = "v2/sw/response/%u/chunk/";
char constexpr SOFTWARE_RESPONSE_SUBSCRIBE_TOPIC[] = "v2/sw/response/+/chunk/+";
char constexpr SOFTWARE_REQUEST_TOPIC[] = "v2/sw/request/%u/chunk/%u";
// Software data keys.
char constexpr CURR_SW_TITLE_KEY[] = "current_sw_title";
char constexpr CURR_SW_VER_KEY[] = "current_sw_version";
char constexpr SW_ERROR_KEY[] = "sw_error";
char constexpr SW_STATE_KEY[] = "sw_state";
char constexpr SW_VER_KEY[] = "sw_version";
char constexpr SW_TITLE_KEY[] = "sw_title";
char constexpr SW_CHKS_KEY[] = "sw_checksum";
char constexpr SW_CHKS_ALGO_KEY[] = "sw_checksum_algorithm";
char constexpr SW_SIZE_KEY[] = "sw_size";
// Log messages.
char constexpr NO_SW[] = "Missing shared attribute software keys. Ensure you "
                         "assigned an OTA update with binary";
char constexpr EMPTY_SW[] = "Received shared attribute software keys were NULL";
char constexpr SW_NOT_FOR_US[] = "Received software title (%s) is different "
                                 "and not meant for this device (%s)";
char constexpr SW_CHKS_ALGO_NOT_SUPPORTED[] =
    "Received software checksum algorithm (%s) is not supported";
char constexpr NOT_ENOUGH_RAM_SW[] =
    "Temporary allocating more internal client buffer failed, decrease OTA "
    "chunk size or decrease overall heap usage";
char constexpr RESETTING_FAILED_SW[] =
    "Preparing for OTA software updates failed, attributes might be NULL";
#if THINGSBOARD_ENABLE_DEBUG
char constexpr PAGE_BREAK_SW[] = "=================================";
char constexpr NEW_SW[] = "A new Software package is available:";
char constexpr FROM_TOO_SW[] = "(%s) => (%s)";
char constexpr DOWNLOADING_SW[] = "Attempting to download over MQTT...";
#endif // THINGSBOARD_ENABLE_DEBUG

/// @brief Handles the internal implementation of the ThingsBoard over the air
/// software update API. See https://thingsboard.io/docs/user-guide/ota-updates/
/// for more information
/// @tparam Logger Implementation that should be used to print error messages
/// generated by internal processes and additional debugging messages if
/// THINGSBOARD_ENABLE_DEBUG is set, default = DefaultLogger
template <typename Logger = DefaultLogger>
class OTA_Software_Update : public IAPI_Implementation {
public:
  /// @brief Constructor
  OTA_Software_Update()
      : m_subscribe_api_callback(), m_send_json_callback(),
        m_send_json_string_callback(), m_subscribe_topic_callback(),
        m_unsubscribe_topic_callback(), m_get_receive_size_callback(),
        m_get_send_size_callback(), m_set_buffer_size_callback(),
        m_get_request_id_callback(), m_sw_callback(),
        m_previous_buffer_size(0U), m_changed_buffer_size(false)
#if THINGSBOARD_ENABLE_STL
        ,
        m_ota(std::bind(&OTA_Software_Update::Publish_Chunk_Request, this,
                        std::placeholders::_1, std::placeholders::_2),
              std::bind(&OTA_Software_Update::Software_Send_State, this,
                        std::placeholders::_1, std::placeholders::_2),
              std::bind(&OTA_Software_Update::Software_OTA_Unsubscribe, this))
#else
        ,
        m_ota(OTA_Software_Update::staticPublishChunk,
              OTA_Software_Update::staticSoftwareSend,
              OTA_Software_Update::staticUnsubscribe)
#endif // THINGSBOARD_ENABLE_STL
        ,
        m_response_topic(), m_sw_attribute_update(), m_sw_attribute_request() {
    (void)snprintf(m_response_topic, sizeof(m_response_topic),
                   SOFTWARE_RESPONSE_TOPIC, 0U);
#if !THINGSBOARD_ENABLE_STL
    m_subscribedInstance = nullptr;
#endif // !THINGSBOARD_ENABLE_STL
  }

  /// @brief Checks if software settings are assigned to the connected device
  /// and if they are attempts to use those settings to start a software update.
  /// Will only be checked once and if there is no software assigned or if the
  /// assigned software is already installed this method will not update. See
  /// https://thingsboard.io/docs/user-guide/ota-updates/ for more information
  /// @param callback Callback method that will be called
  /// @return Whether subscribing the given callback was successful or not
  bool Start_Software_Update(OTA_Update_Callback const &callback) {
    if (!Prepare_Software_Settings(callback)) {
      Logger::printfln(RESETTING_FAILED_SW);
      return false;
    }

    constexpr char const *array[SW_OTA_ATTRIBUTE_KEYS_AMOUNT] = {
        SW_CHKS_KEY, SW_CHKS_ALGO_KEY, SW_SIZE_KEY, SW_TITLE_KEY, SW_VER_KEY};
#if THINGSBOARD_ENABLE_DYNAMIC
#if THINGSBOARD_ENABLE_STL
    const Attribute_Request_Callback sw_request_callback(
        std::bind(&OTA_Software_Update::Software_Shared_Attribute_Received,
                  this, std::placeholders::_1),
        callback.Get_Timeout(),
        std::bind(&OTA_Software_Update::Request_Timeout, this), array + 0U,
        array + SW_OTA_ATTRIBUTE_KEYS_AMOUNT);
#else
    const Attribute_Request_Callback sw_request_callback(
        OTA_Software_Update::onStaticSoftwareReceived, callback.Get_Timeout(),
        OTA_Software_Update::onStaticRequestTimeout, array + 0U,
        array + SW_OTA_ATTRIBUTE_KEYS_AMOUNT);
#endif // THINGSBOARD_ENABLE_STL
#else
#if THINGSBOARD_ENABLE_STL
    const Attribute_Request_Callback<SW_OTA_ATTRIBUTE_KEYS_AMOUNT>
        sw_request_callback(
            std::bind(&OTA_Software_Update::Software_Shared_Attribute_Received,
                      this, std::placeholders::_1),
            callback.Get_Timeout(),
            std::bind(&OTA_Software_Update::Request_Timeout, this), array + 0U,
            array + SW_OTA_ATTRIBUTE_KEYS_AMOUNT);
#else
    const Attribute_Request_Callback<SW_OTA_ATTRIBUTE_KEYS_AMOUNT>
        sw_request_callback(OTA_Software_Update::onStaticSoftwareReceived,
                            callback.Get_Timeout(),
                            OTA_Software_Update::onStaticRequestTimeout,
                            array + 0U, array + SW_OTA_ATTRIBUTE_KEYS_AMOUNT);
#endif // THINGSBOARD_ENABLE_STL
#endif // THINGSBOARD_ENABLE_DYNAMIC
    return m_sw_attribute_request.Shared_Attributes_Request(
        sw_request_callback);
  }

  /// @brief Stops the currently ongoing software update.
  /// See https://thingsboard.io/docs/user-guide/ota-updates/ for more
  /// information
  void Stop_Software_Update() { m_ota.Stop_Firmware_Update(); }

  /// @brief Sends the given software title and software version to the cloud.
  /// @param current_sw_title Current device software title
  /// @param current_sw_version Current device software version
  /// @return Whether sending the current device software information was
  /// successful or not
  bool Software_Send_Info(char const *current_sw_title,
                          char const *current_sw_version) {
    StaticJsonDocument<JSON_OBJECT_SIZE(2)> current_software_info;
    current_software_info[CURR_SW_TITLE_KEY] = current_sw_title;
    current_software_info[CURR_SW_VER_KEY] = current_sw_version;
    return m_send_json_callback.Call_Callback(
        TELEMETRY_TOPIC, current_software_info,
        Helper::Measure_Json(current_software_info));
  }

  /// @brief Sends the given software state to the cloud.
  /// @param current_sw_state Current software download state
  /// @param sw_error Software error message, default = ""
  /// @return Whether sending the current software download state was successful
  /// or not
  bool Software_Send_State(char const *current_sw_state,
                           char const *sw_error = "") {
    StaticJsonDocument<JSON_OBJECT_SIZE(2)> current_software_state;
    current_software_state[SW_ERROR_KEY] = sw_error;
    current_software_state[SW_STATE_KEY] = current_sw_state;
    return m_send_json_callback.Call_Callback(
        TELEMETRY_TOPIC, current_software_state,
        Helper::Measure_Json(current_software_state));
  }

  API_Process_Type Get_Process_Type() const override {
    return API_Process_Type::RAW;
  }

  void Process_Response(char const *topic, uint8_t *payload,
                        unsigned int length) override {
    size_t const &request_id = m_sw_callback.Get_Request_ID();
    char response_topic[Helper::detectSize(SOFTWARE_RESPONSE_TOPIC,
                                           request_id)] = {};
    (void)snprintf(response_topic, sizeof(response_topic),
                   SOFTWARE_RESPONSE_TOPIC, request_id);
    size_t const chunk = Helper::parseRequestId(response_topic, topic);
    m_ota.Process_Firmware_Packet(chunk, payload, length);
  }

  void Process_Json_Response(char const *topic,
                             JsonDocument const &data) override {
    // Nothing to do
  }

  bool Compare_Response_Topic(char const *topic) const override {
    return strncmp(m_response_topic, topic, strlen(m_response_topic)) == 0;
  }

  bool Unsubscribe() override {
    Stop_Software_Update();
    return true;
  }

  bool Resubscribe_Topic() override { return Software_OTA_Subscribe(); }

#if !THINGSBOARD_USE_ESP_TIMER
  void loop() override { m_ota.update(); }
#endif // !THINGSBOARD_USE_ESP_TIMER

  void Initialize() override {
    m_subscribe_api_callback.Call_Callback(m_sw_attribute_update);
    m_subscribe_api_callback.Call_Callback(m_sw_attribute_request);
  }

  void Set_Client_Callbacks(
      Callback<void, IAPI_Implementation &>::function subscribe_api_callback,
      Callback<bool, char const *const, JsonDocument const &,
               size_t const &>::function send_json_callback,
      Callback<bool, char const *const, char const *const>::function
          send_json_string_callback,
      Callback<bool, char const *const>::function subscribe_topic_callback,
      Callback<bool, char const *const>::function unsubscribe_topic_callback,
      Callback<uint16_t>::function get_receive_size_callback,
      Callback<uint16_t>::function get_send_size_callback,
      Callback<bool, uint16_t, uint16_t>::function set_buffer_size_callback,
      Callback<size_t *>::function get_request_id_callback) override {
    m_subscribe_api_callback.Set_Callback(subscribe_api_callback);
    m_send_json_callback.Set_Callback(send_json_callback);
    m_send_json_string_callback.Set_Callback(send_json_string_callback);
    m_subscribe_topic_callback.Set_Callback(subscribe_topic_callback);
    m_unsubscribe_topic_callback.Set_Callback(unsubscribe_topic_callback);
    m_get_receive_size_callback.Set_Callback(get_receive_size_callback);
    m_get_send_size_callback.Set_Callback(get_send_size_callback);
    m_set_buffer_size_callback.Set_Callback(set_buffer_size_callback);
    m_get_request_id_callback.Set_Callback(get_request_id_callback);
  }

private:
  bool Prepare_Software_Settings(OTA_Update_Callback const &callback) {
    char const *current_sw_title = callback.Get_Firmware_Title();
    char const *current_sw_version = callback.Get_Firmware_Version();

    if (Helper::stringIsNullorEmpty(current_sw_title) ||
        Helper::stringIsNullorEmpty(current_sw_version)) {
      return false;
    } else if (!Software_Send_Info(current_sw_title, current_sw_version)) {
      return false;
    }

    size_t *p_request_id = m_get_request_id_callback.Call_Callback();
    if (p_request_id == nullptr) {
      Logger::printfln(REQUEST_ID_NULL);
      return false;
    }
    auto &request_id = *p_request_id;

    m_sw_callback = callback;
    m_sw_callback.Set_Request_ID(++request_id);
    (void)snprintf(m_response_topic, sizeof(m_response_topic),
                   SOFTWARE_RESPONSE_TOPIC, request_id);
    return true;
  }

  bool Software_OTA_Subscribe() {
    if (!m_subscribe_topic_callback.Call_Callback(
            SOFTWARE_RESPONSE_SUBSCRIBE_TOPIC)) {
      char message[strlen(SUBSCRIBE_TOPIC_FAILED) +
                   strlen(SOFTWARE_RESPONSE_SUBSCRIBE_TOPIC) + 2] = {};
      (void)snprintf(message, sizeof(message), SUBSCRIBE_TOPIC_FAILED,
                     SOFTWARE_RESPONSE_SUBSCRIBE_TOPIC);
      Logger::printfln(message);
      Software_Send_State(FW_STATE_FAILED, message);
      return false;
    }
    return true;
  }

  bool Software_OTA_Unsubscribe() {
    if (m_changed_buffer_size) {
      (void)m_set_buffer_size_callback.Call_Callback(
          m_previous_buffer_size, m_get_send_size_callback.Call_Callback());
    }
    m_sw_callback = OTA_Update_Callback();
    return m_unsubscribe_topic_callback.Call_Callback(
        SOFTWARE_RESPONSE_SUBSCRIBE_TOPIC);
  }

  bool Publish_Chunk_Request(size_t const &request_id,
                             size_t const &request_chunck) {
    uint16_t const &chunk_size = m_sw_callback.Get_Chunk_Size();

    char size[Helper::detectSize(NUMBER_PRINTF, chunk_size)] = {};
    (void)snprintf(size, sizeof(size), NUMBER_PRINTF, chunk_size);

    char topic[Helper::detectSize(SOFTWARE_REQUEST_TOPIC, request_id,
                                  request_chunck)] = {};
    (void)snprintf(topic, sizeof(topic), SOFTWARE_REQUEST_TOPIC, request_id,
                   request_chunck);
    return m_send_json_string_callback.Call_Callback(topic, size);
  }

  void Request_Timeout() {
    Logger::printfln(NO_SW_REQUEST_RESPONSE);
    Software_Send_State(FW_STATE_FAILED, NO_SW_REQUEST_RESPONSE);
  }

  void Software_Shared_Attribute_Received(JsonObjectConst const &data) {
    if (!data.containsKey(SW_VER_KEY) || !data.containsKey(SW_TITLE_KEY) ||
        !data.containsKey(SW_CHKS_KEY) || !data.containsKey(SW_CHKS_ALGO_KEY) ||
        !data.containsKey(SW_SIZE_KEY)) {
      Logger::printfln(NO_SW);
      Software_Send_State(FW_STATE_FAILED, NO_SW);
      return;
    }

    char const *sw_title = data[SW_TITLE_KEY];
    char const *sw_version = data[SW_VER_KEY];
    char const *sw_checksum = data[SW_CHKS_KEY];
    char const *sw_algorithm = data[SW_CHKS_ALGO_KEY];
    size_t const sw_size = data[SW_SIZE_KEY];

    char const *curr_sw_title = m_sw_callback.Get_Firmware_Title();
    char const *curr_sw_version = m_sw_callback.Get_Firmware_Version();

    if (sw_title == nullptr || sw_version == nullptr ||
        curr_sw_title == nullptr || curr_sw_version == nullptr ||
        sw_algorithm == nullptr || sw_checksum == nullptr) {
      Logger::printfln(EMPTY_SW);
      Software_Send_State(FW_STATE_FAILED, EMPTY_SW);
      return;
    } else if (strlen(curr_sw_title) == strlen(sw_title) &&
               strncmp(curr_sw_title, sw_title, strlen(curr_sw_title)) == 0 &&
               strlen(curr_sw_version) == strlen(sw_version) &&
               strncmp(curr_sw_version, sw_version, strlen(curr_sw_version)) ==
                   0) {
      Software_Send_State(FW_STATE_UPDATED);
      return;
    } else if (strlen(curr_sw_title) != strlen(sw_title) ||
               strncmp(curr_sw_title, sw_title, strlen(curr_sw_title)) != 0) {
      char message[strlen(SW_NOT_FOR_US) + strlen(sw_title) +
                   strlen(curr_sw_title) + 3] = {};
      (void)snprintf(message, sizeof(message), SW_NOT_FOR_US, sw_title,
                     curr_sw_title);
      Logger::printfln(message);
      Software_Send_State(FW_STATE_FAILED, message);
      return;
    }

    mbedtls_md_type_t sw_checksum_algorithm = mbedtls_md_type_t{};

    if (strncmp(CHECKSUM_AGORITM_MD5, sw_algorithm,
                strlen(CHECKSUM_AGORITM_MD5)) == 0) {
      sw_checksum_algorithm = mbedtls_md_type_t::MBEDTLS_MD_MD5;
    } else if (strncmp(CHECKSUM_AGORITM_SHA256, sw_algorithm,
                       strlen(CHECKSUM_AGORITM_SHA256)) == 0) {
      sw_checksum_algorithm = mbedtls_md_type_t::MBEDTLS_MD_SHA256;
    } else if (strncmp(CHECKSUM_AGORITM_SHA384, sw_algorithm,
                       strlen(CHECKSUM_AGORITM_SHA384)) == 0) {
      sw_checksum_algorithm = mbedtls_md_type_t::MBEDTLS_MD_SHA384;
    } else if (strncmp(CHECKSUM_AGORITM_SHA512, sw_algorithm,
                       strlen(CHECKSUM_AGORITM_SHA512)) == 0) {
      sw_checksum_algorithm = mbedtls_md_type_t::MBEDTLS_MD_SHA512;
    } else {
      char message[strlen(SW_CHKS_ALGO_NOT_SUPPORTED) + strlen(sw_algorithm) +
                   2] = {};
      (void)snprintf(message, sizeof(message), SW_CHKS_ALGO_NOT_SUPPORTED,
                     sw_algorithm);
      Logger::printfln(message);
      Software_Send_State(FW_STATE_FAILED, message);
      return;
    }

    m_sw_callback.Call_Update_Starting_Callback();
    bool const result = Software_OTA_Subscribe();
    if (!result) {
      m_sw_callback.Call_Callback(result);
      return;
    }

#if THINGSBOARD_ENABLE_DEBUG
    Logger::printfln(PAGE_BREAK_SW);
    Logger::printfln(NEW_SW);
    char software[strlen(FROM_TOO_SW) + strlen(curr_sw_version) +
                  strlen(sw_version) + 3] = {};
    (void)snprintf(software, sizeof(software), FROM_TOO_SW, curr_sw_version,
                   sw_version);
    Logger::printfln(software);
    Logger::printfln(DOWNLOADING_SW);
#endif // THINGSBOARD_ENABLE_DEBUG

    const uint16_t &chunk_size = m_sw_callback.Get_Chunk_Size();

    m_previous_buffer_size = m_get_receive_size_callback.Call_Callback();
    m_changed_buffer_size = m_previous_buffer_size < (chunk_size + 50U);

    if (m_changed_buffer_size &&
        !m_set_buffer_size_callback.Call_Callback(
            chunk_size + 50U, m_get_send_size_callback.Call_Callback())) {
      Logger::printfln(NOT_ENOUGH_RAM_SW);
      Software_Send_State(FW_STATE_FAILED, NOT_ENOUGH_RAM_SW);
      m_sw_callback.Call_Callback(false);
      return;
    }

    m_ota.Start_Firmware_Update(m_sw_callback, sw_size, sw_checksum,
                                sw_checksum_algorithm);
  }

#if !THINGSBOARD_ENABLE_STL
  static void onStaticSoftwareReceived(JsonDocument const &data) {
    if (m_subscribedInstance == nullptr) {
      return;
    }
    m_subscribedInstance->Software_Shared_Attribute_Received(data);
  }

  static void onStaticRequestTimeout() {
    if (m_subscribedInstance == nullptr) {
      return;
    }
    m_subscribedInstance->Request_Timeout();
  }

  static bool staticPublishChunk(size_t const &request_id,
                                 size_t const &request_chunck) {
    if (m_subscribedInstance == nullptr) {
      return false;
    }
    return m_subscribedInstance->Publish_Chunk_Request(request_id,
                                                       request_chunck);
  }

  static bool staticSoftwareSend(char const *current_sw_state,
                                 char const *sw_error = nullptr) {
    if (m_subscribedInstance == nullptr) {
      return false;
    }
    return m_subscribedInstance->Software_Send_State(current_sw_state,
                                                     sw_error);
  }

  static bool staticUnsubscribe() {
    if (m_subscribedInstance == nullptr) {
      return false;
    }
    return m_subscribedInstance->Software_OTA_Unsubscribe();
  }

  static OTA_Software_Update *m_subscribedInstance;
#endif // !THINGSBOARD_ENABLE_STL

  Callback<void, IAPI_Implementation &> m_subscribe_api_callback = {};
  Callback<bool, char const *const, JsonDocument const &, size_t const &>
      m_send_json_callback = {};
  Callback<bool, char const *const, char const *const>
      m_send_json_string_callback = {};
  Callback<bool, char const *const> m_subscribe_topic_callback = {};
  Callback<bool, char const *const> m_unsubscribe_topic_callback = {};
  Callback<uint16_t> m_get_receive_size_callback = {};
  Callback<uint16_t> m_get_send_size_callback = {};
  Callback<bool, uint16_t, uint16_t> m_set_buffer_size_callback = {};
  Callback<size_t *> m_get_request_id_callback = {};

  OTA_Update_Callback m_sw_callback = {};
  uint16_t m_previous_buffer_size = {};
  bool m_changed_buffer_size = {};
  OTA_Handler<Logger> m_ota = {};
  char m_response_topic[MAX_SW_TOPIC_SIZE] = {};
#if !THINGSBOARD_ENABLE_DYNAMIC
  Shared_Attribute_Update<1U, SW_OTA_ATTRIBUTE_KEYS_AMOUNT, Logger>
      m_sw_attribute_update = {};
  Attribute_Request<1U, SW_OTA_ATTRIBUTE_KEYS_AMOUNT, Logger>
      m_sw_attribute_request = {};
#else
  Shared_Attribute_Update<Logger> m_sw_attribute_update = {};
  Attribute_Request<Logger> m_sw_attribute_request = {};
#endif // !THINGSBOARD_ENABLE_DYNAMIC
};

#if !THINGSBOARD_ENABLE_STL
OTA_Software_Update *OTA_Software_Update::m_subscribedInstance = nullptr;
#endif

#endif // OTA_Software_Update_h
